import Head from 'next/head'
import Navbar from '../../components/common/Navbar'

export default function Create() {
  return (
    <>
      <Navbar />
      <div className='text-center'>
        <Head>
          <title>Explore | Recon</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <h1 className='mx-auto my-4 text-white text-4xl font-bold'>Create</h1>
      </div>
    </>
  )
}