import Head from 'next/head'
import Navbar from '../../components/common/Navbar'
import { FiUpload } from 'react-icons/fi'
import { useState } from 'react'

export default function Create() {
  const [clipFileName, setClipFileName] = useState('')
  const [thumbnailFileName, setThumbnailFileName] = useState('')

  const [name, setName] = useState('')
  const [desc, setDesc] = useState('')
  const [game, setGame] = useState('Valorant')
  const [tag, setTag] = useState('Competitive')
  const [price, setPrice] = useState('')

  function openClipInput() {
    var inputEl = document.getElementById('clip-upload')
    inputEl.click()
  }

  function openThumbnailInput() {
    var inputEl = document.getElementById('thumbnail-upload')
    inputEl.click()
  }

  function onClipUpload() {
    var inputEl = document.getElementById('clip-upload')
    setClipFileName(inputEl.files.item(0).name)
  }

  function onThumbnailUpload() {
    var inputEl = document.getElementById('thumbnail-upload')
    setThumbnailFileName(inputEl.files.item(0).name)
  }

  function onSubmitNFT() {
    console.log(name)
    console.log(desc)
    console.log(game)
    console.log(tag)
    console.log(price)
  }

  return (
    <>
      <Navbar />
      <div className='text-center'>
        <Head>
          <title>Explore | Recon</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <div className='mx-16'>
          <h1 className='my-4 text-primary text-2xl text-left font-bold'>Create your NFT</h1>
          <main className='flex flex-row justify-evenly'>
            <div>
              <h3 className='text-xl text-left my-3 font-semibold text-primary'>Upload clip</h3>
              <div className='w-80 h-80 flex border-2 border-primary cursor-pointer' onClick={openClipInput}>
                <input type='file' id='clip-upload' className='w-full h-full hidden' onChange={onClipUpload} />
                <FiUpload className='text-7xl mx-auto my-auto text-primary' />
              </div>
              <p className='my-2 text-primary text-sm'>{clipFileName}</p>
            </div>
            <div>
              <h3 className='text-xl text-left my-3 font-semibold text-primary'>Thumbnail</h3>
              <div className='w-80 h-80 flex border-2 border-primary cursor-pointer' onClick={openThumbnailInput}>
                <input type='file' id='thumbnail-upload' className='w-full h-full hidden' onChange={onThumbnailUpload} />
                <FiUpload className='text-7xl mx-auto my-auto text-primary' />
              </div>
              <p className='my-2 text-primary text-sm'>{thumbnailFileName}</p>
            </div>
          </main>
          <div className=''>
            <h3 className='text-primary text-xl text-left font-semibold my-3'>Name</h3>
            <input type='text' onChange={e => setName(e.target.value)} placeholder='Every sick clip deserves a great name!' className='my-3 text-primary border-2 border-primary mx-auto w-full outline-none bg-gray py-2 px-4 rounded-lg' />
            <h3 className='text-primary text-xl text-left font-semibold my-3'>Description</h3>
            <textarea onChange={e => setDesc(e.target.value)} placeholder='Tell the world about everything this clip contains.......' rows='6' className='my-3 text-primary border-2 border-primary mx-auto w-full outline-none bg-gray py-2 px-4 rounded-lg' />
            <div className='flex flex-row w-full justify-evenly'>
              <div className='w-1/2'>
                <h3 className='text-primary text-xl text-left font-semibold my-3'>Game</h3>
                <select onChange={e => setGame(e.target.value)} className='my-3 float-left px-4 py-2 bg-gray-light text-primary outline-none rounded-lg'>
                  <option>Valorant</option>
                  <option>CS:GO</option>
                  <option>Fortnite</option>
                </select>
              </div>
              <div className='w-1/2'>
                <h3 className='text-primary text-xl text-left font-semibold my-3'>Tag</h3>
                <select onChange={e => setTag(e.target.value)} className='my-3 float-left px-4 py-2 bg-gray-light text-primary outline-none rounded-lg'>
                  <option>Competitive</option>
                  <option>Casual</option>
                </select>
              </div>
            </div>
            <h3 className='text-primary text-xl text-left font-semibold my-3'>Listing Price</h3>
            <input type='text' onChange={e => setPrice(e.target.value)} placeholder='Set the base price at which you would like to list this clip....' className='my-3 text-primary border-2 border-primary mx-auto w-full outline-none bg-gray py-2 px-4 rounded-lg' />
            <button onClick={onSubmitNFT} className='my-3 float-left bg-primary text-black text-xl px-8 py-1 font-semibold rounded-lg'>Create</button>
          </div>
        </div>
      </div>
    </>
  )
}