import Head from 'next/head'
import Image from 'next/Image'
import { useState } from 'react'
import Navbar from '../../components/common/Navbar'

import pfp from '../../public/pfp.png'

export default function Profile({ ownedNFTs, createdNFTs, soldNFTs }) {
  const [tab, setTab] = useState('owned')

  return (
    <>
      <Head>
        <title>Profile | Recon</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='h-screen flex flex-col overflow-hidden'>
        <Navbar />
        <div className='flex flex-row text-center overflow-hidden'>
          <div className='w-1/5 flex flex-col items-start text-left border-r-2 border-gray-light px-6 pt-4'>
            <ProfileInfo />
          </div>
          <div className='w-4/5 px-6 pt-4 overflow-y-scroll'>
            <MyNFTs tab={tab} setTab={setTab} ownedNFTs={ownedNFTs} createdNFTs={createdNFTs} soldNFTs={soldNFTs} />
          </div>
        </div>
      </div>
    </>
  )
}

const ProfileInfo = () => {
  return (
    <>
      <div className='my-3 rounded-lg'>
        <Image
          className='cursor-pointer'
          src={pfp}
          width={180}
          height={180}
        />
      </div>
      <h6 className='mt-3 text-gray-mute font-semibold text-lg'>Description</h6>
      <p className='mb-3 text-primary text-sm'>Temporary shit</p>
      <h6 className='mt-3 text-gray-mute font-semibold text-lg'>Clips Minted</h6>
      <p className='mb-3 text-primary text-sm'>45K</p>
      <h6 className='mt-3 text-gray-mute font-semibold text-lg'>Clips Sold</h6>
      <p className='mb-3 text-primary text-sm'>29K</p>
      <h6 className='mt-3 text-gray-mute font-semibold text-lg'>Creators</h6>
      <p className='mb-3 text-primary text-sm'>8.4K</p>
    </>
  )
}

const MyNFTs = ({ tab, setTab, ownedNFTs, createdNFTs, soldNFTs }) => {
  switch (tab) {
    case 'owned':
      return (
        <>
          <div className='flex flex-row w-full justify-start'>
            <button className='text-xl px-12 mr-2 py-2 bg-primary text-black font-bold rounded-xl'>Owned</button>
            <button onClick={() => setTab('created')} className='text-xl px-12 ml-2 py-2 text-white font-bold rounded-xl'>Created</button>
            <button onClick={() => setTab('sold')} className='text-xl px-12 ml-2 py-2 text-white font-bold rounded-xl'>Sold</button>
          </div>
          <div className='my-6 mx-16 grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-8'>
            {ownedNFTs.map((NFT) => <ClipCard NFT={NFT} />)}
          </div>
        </>
      )
    case 'created':
      return (
        <>
          <div className='flex flex-row w-full justify-start'>
            <button onClick={() => setTab('owned')} className='text-xl px-12 mr-2 py-2 text-white font-bold rounded-xl'>Owned</button>
            <button className='text-xl px-12 ml-2 py-2 bg-primary text-black font-bold rounded-xl'>Created</button>
            <button onClick={() => setTab('sold')} className='text-xl px-12 ml-2 py-2 text-white font-bold rounded-xl'>Sold</button>
          </div>
          <div className='my-6 mx-16 grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-8'>
            {createdNFTs.map((NFT) => <ClipCard NFT={NFT} />)}
          </div>
        </>
      )
    case 'sold':
      return (
        <>
          <div className='flex flex-row w-full justify-start'>
            <button onClick={() => setTab('owned')} className='text-xl px-12 mr-2 py-2 text-white font-bold rounded-xl'>Owned</button>
            <button onClick={() => setTab('created')} className='text-xl px-12 ml-2 py-2 text-white font-bold rounded-xl'>Created</button>
            <button className='text-xl px-12 ml-2 py-2 bg-primary text-black font-bold rounded-xl'>Sold</button>
          </div>
          <div className='my-6 mx-16 grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-8'>
            {soldNFTs.map((NFT) => <ClipCard NFT={NFT} />)}
          </div>
        </>
      )
    default:
      return null
  }
}