import Head from 'next/head'
import Image from 'next/Image'
import { useState } from 'react'
import Navbar from '../../components/Navbar'
import ClipCard from '../../components/ClipCard'

import pfp from '../../public/pfp.png'

export default function Profile({ ownedNFTs, createdNFTs, soldNFTs, walletAddress }) {
  const [tab, setTab] = useState('owned')

  return (
    <>
      <Head>
        <title>Profile | Recon</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='h-screen flex flex-col overflow-hidden'>
        <Navbar />
        <div className='flex h-full flex-row text-center overflow-hidden'>
          {walletAddress ? <>
            <div className='w-1/4 h-full text-center py-12 px-6'>
              <ProfileInfo
                totalOwned={ownedNFTs.length}
                totalCreated={createdNFTs.length}
                totalSold={soldNFTs.length}
                walletAddress={walletAddress}
              />
            </div>
            <div className='w-3/4 px-6 pt-4 overflow-y-scroll'>
              <MyNFTs
                tab={tab}
                setTab={setTab}
                ownedNFTs={ownedNFTs}
                createdNFTs={createdNFTs}
                soldNFTs={soldNFTs}
              />
            </div>
          </> : <h1 className='m-auto text-center text-xl text-primary'>Connect your MetaMask wallet to access this page.</h1>}
        </div>
      </div>
    </>
  )
}

const ProfileInfo = ({ walletAddress, totalOwned, totalCreated, totalSold }) => {
  return (
    <div className='h-full w-full p-2 flex flex-col items-center justify-evenly rounded-lg bg-gray-light'>
      <div>
        <Image
          className='mt-3 cursor-pointer'
          src={pfp}
          width={120}
          height={120}
        />
        <h6 className='mt-3 text-gray-mute font-semibold text-xs'>{walletAddress}</h6>
      </div>
      <div className='w-4/5'>
        <div className='flex flex-row justify-between mb-3 text-white text-base font-semibold'><span>Total Owned</span><span>{totalOwned}</span></div>
        <div className='flex flex-row justify-between mb-3 text-white text-base font-semibold'><span>Total Created</span><span>{totalCreated}</span></div>
        <div className='flex flex-row justify-between mb-3 text-white text-base font-semibold'><span>Total Sold</span><span>{totalSold}</span></div>
      </div >
    </div >
  )
}

const MyNFTs = ({ tab, setTab, ownedNFTs, createdNFTs, soldNFTs }) => {
  switch (tab) {
    case 'owned':
      return (
        <>
          <div className='flex flex-row w-full justify-start'>
            <button className='text-xl px-12 mr-2 py-2 bg-primary text-black font-bold rounded-xl'>Owned</button>
            <button onClick={() => setTab('created')} className='text-xl px-12 ml-2 py-2 text-white font-bold rounded-xl'>Created</button>
            <button onClick={() => setTab('sold')} className='text-xl px-12 ml-2 py-2 text-white font-bold rounded-xl'>Sold</button>
          </div>
          <div className='my-6 mx-16 grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-8'>
            {ownedNFTs.map((NFT) => <ClipCard NFT={NFT} />)}
          </div>
        </>
      )
    case 'created':
      return (
        <>
          <div className='flex flex-row w-full justify-start'>
            <button onClick={() => setTab('owned')} className='text-xl px-12 mr-2 py-2 text-white font-bold rounded-xl'>Owned</button>
            <button className='text-xl px-12 ml-2 py-2 bg-primary text-black font-bold rounded-xl'>Created</button>
            <button onClick={() => setTab('sold')} className='text-xl px-12 ml-2 py-2 text-white font-bold rounded-xl'>Sold</button>
          </div>
          <div className='my-6 mx-16 grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-8'>
            {createdNFTs.map((NFT) => <ClipCard NFT={NFT} />)}
          </div>
        </>
      )
    case 'sold':
      return (
        <>
          <div className='flex flex-row w-full justify-start'>
            <button onClick={() => setTab('owned')} className='text-xl px-12 mr-2 py-2 text-white font-bold rounded-xl'>Owned</button>
            <button onClick={() => setTab('created')} className='text-xl px-12 ml-2 py-2 text-white font-bold rounded-xl'>Created</button>
            <button className='text-xl px-12 ml-2 py-2 bg-primary text-black font-bold rounded-xl'>Sold</button>
          </div>
          <div className='my-6 mx-16 grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-8'>
            {soldNFTs.map((NFT) => <ClipCard NFT={NFT} />)}
          </div>
        </>
      )
    default:
      return null
  }
}