import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import { Player } from 'video-react'
import { FiHeart } from 'react-icons/fi'
import { FaRegDotCircle } from 'react-icons/fa'

import Navbar from '../../components/common/Navbar'

export default function NFT() {
  const router = useRouter()
  const { nftId } = router.query
  console.log(nftId);

  return (
    <>
      <Head>
        <title>{nftId} | Recon</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='h-screen flex flex-col overflow-hidden'>
        <Navbar />
        <div className='flex flex-col md:flex-row'>
          <div className='w-2/3 p-6'>
            <Player
              playsInline
              poster='/assets/poster.png'
              src='https://media.w3.org/2010/05/sintel/trailer_hd.mp4'
            />
          </div>
          <div className='w-1/3 flex flex-col justify-center px-8'>
            <h6 className='my-1 text-gray-mute text-lg font-semibold'>Valorant</h6>
            <h1 className='my-1 text-2xl text-white font-bold'>Insane spray transfer 3K on Bind!</h1>
            <div className='my-1 flex flex-row text-base justify-between items-center'>
              <h6 className='text-gray-mute'>Created by <span className='text-primary'>mizanxali</span></h6>
              <h6 className='text-white '>
                <FaRegDotCircle className='text-yellow inline mx-1' />
                Competitive
              </h6>
              <h6 className='text-gray-mute'>
                <FiHeart className='text-red inline mx-1' />
                167
              </h6>
            </div>
            <p className='my-1 text-lg text-white font-semibold'>The clip consists of a play from Beta mode of Valorant which makes it extremely rare.</p>
            <h3 className='my-1 text-white text-xl'>0.8 ETH <span className='text-gray-mute'>($0.1368)</span></h3>
            <button className='my-1 w-1/3 bg-primary text-black text-lg px-2 py-1 font-semibold rounded-lg'>Buy Now</button>
          </div>
        </div>
      </div>
    </>
  )
}