import Head from 'next/head'
import Navbar from '../components/common/Navbar'
import Footer from '../components/common/Footer'

export default function Home() {
  return (
    <>
      <Navbar />
      <div className='text-center'>
        <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <h1 className='mx-auto my-4 text-white text-4xl font-bold'>Hello world</h1>
      </div>
      <Footer />
    </>
  )
}

